[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/company"
  to = "/.netlify/functions/company"
  status = 200

[[redirects]]
  from = "/api/send-otp"
  to = "/.netlify/functions/send-otp"
  status = 200

[[redirects]]
  from = "/api/verify-otp"
  to = "/.netlify/functions/verify-otp"
  status = 200

[[redirects]]
  from = "/api/save-photo"
  to = "/.netlify/functions/save-photo"
  status = 200

[[redirects]]
  from = "/api/photo"
  to = "/.netlify/functions/photo"
  status = 200
